apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  type: NodePort
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
