apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavaialble: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/assignment3-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
          #image: mdrohanfz/assignment3-web:latest
          image: mdrohanfz/assignment3-web-v2:part7
          name: web
          #livenessProbe:
          #  httpGet:
          #    path: /health
          #    port: 7777
          #readinessProbe:
          #  httpGet:
          #    path: /ready
          #    port: 7777
          ports:
            - containerPort: 7777
              hostPort: 7777
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
